/* Generated By:JavaCC: Do not edit this line. SpelParserConstants.java */
package org.apache.taglibs.standard.lang.spel.parser;

public interface SpelParserConstants {

  int EOF = 0;
  int INTEGER_LITERAL = 6;
  int FLOATING_POINT_LITERAL = 7;
  int EXPONENT = 8;
  int SIGN = 9;
  int STRING_LITERAL = 10;
  int TRUE = 11;
  int FALSE = 12;
  int NULL = 13;
  int PAGE = 14;
  int REQUEST = 15;
  int SESSION = 16;
  int APP = 17;
  int HEADER = 18;
  int PARAM = 19;
  int PARAMVALUES = 20;
  int AND = 21;
  int OR = 22;
  int NOT = 23;
  int EQ_VALUE = 24;
  int NE_VALUE = 25;
  int LT_VALUE = 26;
  int GT_VALUE = 27;
  int LE_VALUE = 28;
  int GE_VALUE = 29;
  int INSTANCEOF = 30;
  int IDENTIFIER = 31;
  int LETTER = 32;
  int DIGIT = 33;
  int COLON = 34;
  int DOT = 35;
  int GT = 36;
  int LT = 37;
  int EQ = 38;
  int LE = 39;
  int GE = 40;
  int NE = 41;
  int START_BRACKET = 42;
  int END_BRACKET = 43;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<SIGN>",
    "<STRING_LITERAL>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"page\"",
    "\"request\"",
    "\"session\"",
    "\"app\"",
    "\"header\"",
    "\"param\"",
    "\"paramvalues\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"eq\"",
    "\"ne\"",
    "\"lt\"",
    "\"gt\"",
    "\"le\"",
    "\"ge\"",
    "\"instanceof\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\":\"",
    "\".\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"[\"",
    "\"]\"",
  };

}
