/*
 * Copyright 1999,2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */ 

/* Generated By:JJTree: Do not edit this line. ParserTreeConstants.java */

package org.apache.taglibs.standard.lang.jpath.expression;

public interface ParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTOROPERATOR = 2;
  public int JJTANDOPERATOR = 3;
  public int JJTEQUALSOPERATOR = 4;
  public int JJTNOTEQUALSOPERATOR = 5;
  public int JJTLESSTHANOPERATOR = 6;
  public int JJTGREATERTHANOPERATOR = 7;
  public int JJTLESSTHANEQUALOPERATOR = 8;
  public int JJTGREATERTHANEQUALOPERATOR = 9;
  public int JJTADDITIONOPERATOR = 10;
  public int JJTSUBTRACTIONOPERATOR = 11;
  public int JJTMULTIPLICATIONOPERATOR = 12;
  public int JJTDIVISIONOPERATOR = 13;
  public int JJTMODULUSOPERATOR = 14;
  public int JJTUNIONOPERATOR = 15;
  public int JJTINTROSPECTIONOPERATOR = 16;
  public int JJTFILTEROPERATOR = 17;
  public int JJTPREDICATE = 18;
  public int JJTBOOLEANFUNCTION = 19;
  public int JJTNUMBERFUNCTION = 20;
  public int JJTSTRINGFUNCTION = 21;
  public int JJTNOTFUNCTION = 22;
  public int JJTFLOORFUNCTION = 23;
  public int JJTCEILINGFUNCTION = 24;
  public int JJTROUNDFUNCTION = 25;
  public int JJTFORMATNUMBERFUNCTION = 26;
  public int JJTCONCATFUNCTION = 27;
  public int JJTENCODEURLFUNCTION = 28;
  public int JJTENCODEHTMLFUNCTION = 29;
  public int JJTSTRINGLENGTHFUNCTION = 30;
  public int JJTSUBSTRINGFUNCTION = 31;
  public int JJTSTARTSWITHFUNCTION = 32;
  public int JJTCONTAINSFUNCTION = 33;
  public int JJTSUBSTRINGBEFOREFUNCTION = 34;
  public int JJTSUBSTRINGAFTERFUNCTION = 35;
  public int JJTTRANSLATEFUNCTION = 36;
  public int JJTPOSITIONFUNCTION = 37;
  public int JJTCURRENTFUNCTION = 38;
  public int JJTLASTFUNCTION = 39;
  public int JJTCOUNTFUNCTION = 40;
  public int JJTSUMFUNCTION = 41;
  public int JJTNOWFUNCTION = 42;
  public int JJTDATEFUNCTION = 43;
  public int JJTFORMATDATEFUNCTION = 44;
  public int JJTROLLDATEFUNCTION = 45;
  public int JJTADDDATEFUNCTION = 46;
  public int JJTTOKENIZEFUNCTION = 47;
  public int JJTUSERFUNCTION = 48;
  public int JJTSCOPELIMITOPERATOR = 49;
  public int JJTIDENTIFIER = 50;
  public int JJTSCOPELIMITNAME = 51;
  public int JJTBOOLEANLITERAL = 52;
  public int JJTNUMBERLITERAL = 53;
  public int JJTSTRINGLITERAL = 54;
  public int JJTLISTLITERAL = 55;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "OrOperator",
    "AndOperator",
    "EqualsOperator",
    "NotEqualsOperator",
    "LessThanOperator",
    "GreaterThanOperator",
    "LessThanEqualOperator",
    "GreaterThanEqualOperator",
    "AdditionOperator",
    "SubtractionOperator",
    "MultiplicationOperator",
    "DivisionOperator",
    "ModulusOperator",
    "UnionOperator",
    "IntrospectionOperator",
    "FilterOperator",
    "Predicate",
    "BooleanFunction",
    "NumberFunction",
    "StringFunction",
    "NotFunction",
    "FloorFunction",
    "CeilingFunction",
    "RoundFunction",
    "FormatNumberFunction",
    "ConcatFunction",
    "EncodeUrlFunction",
    "EncodeHtmlFunction",
    "StringLengthFunction",
    "SubstringFunction",
    "StartsWithFunction",
    "ContainsFunction",
    "SubstringBeforeFunction",
    "SubstringAfterFunction",
    "TranslateFunction",
    "PositionFunction",
    "CurrentFunction",
    "LastFunction",
    "CountFunction",
    "SumFunction",
    "NowFunction",
    "DateFunction",
    "FormatDateFunction",
    "RollDateFunction",
    "AddDateFunction",
    "TokenizeFunction",
    "UserFunction",
    "ScopeLimitOperator",
    "Identifier",
    "ScopeLimitName",
    "BooleanLiteral",
    "NumberLiteral",
    "StringLiteral",
    "ListLiteral",
  };
}
