/*
 * Copyright 1999,2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */ 

/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package org.apache.taglibs.standard.lang.jpath.expression;

public interface ParserConstants {

  int EOF = 0;
  int DIV = 6;
  int MULT = 7;
  int MOD = 8;
  int PLUS = 9;
  int MINUS = 10;
  int EQ = 11;
  int NEQ = 12;
  int LT = 13;
  int LTE = 14;
  int GT = 15;
  int GTE = 16;
  int INTROSPECT = 17;
  int UNION = 18;
  int SCOPE_LIMIT = 19;
  int AND = 20;
  int OR = 21;
  int LIST_BEGIN = 22;
  int LIST_END = 23;
  int SEPARATOR = 24;
  int FUNCTION_BEGIN = 25;
  int FUNCTION_END = 26;
  int PREDICATE_BEGIN = 27;
  int PREDICATE_END = 28;
  int SCOPE_LIMIT_NAME = 58;
  int BOOLEAN_LITERAL = 59;
  int STRING_LITERAL = 60;
  int DIGIT = 61;
  int NUMBER_LITERAL = 62;
  int IDENTIFIER = 63;
  int LETTER = 64;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"/\"",
    "\"*\"",
    "\"%\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\".\"",
    "\"|\"",
    "\":\"",
    "\"and\"",
    "\"or\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"boolean(\"",
    "\"number(\"",
    "\"string(\"",
    "\"not(\"",
    "\"floor(\"",
    "\"ceiling(\"",
    "\"round(\"",
    "\"format-number(\"",
    "\"concat(\"",
    "\"encode-url(\"",
    "\"encode-html(\"",
    "\"string-length(\"",
    "\"substring(\"",
    "\"starts-with(\"",
    "\"contains(\"",
    "\"substring-before(\"",
    "\"substring-after(\"",
    "\"translate(\"",
    "\"position(\"",
    "\"current(\"",
    "\"last(\"",
    "\"count(\"",
    "\"sum(\"",
    "\"now(\"",
    "\"date(\"",
    "\"format-date(\"",
    "\"roll-date(\"",
    "\"add-date(\"",
    "\"tokenize(\"",
    "<SCOPE_LIMIT_NAME>",
    "<BOOLEAN_LITERAL>",
    "<STRING_LITERAL>",
    "<DIGIT>",
    "<NUMBER_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
  };

}
