/* Generated By:JavaCC: Do not edit this line. ELParserConstants.java */
package org.apache.taglibs.standard.lang.jstl.parser;

public interface ELParserConstants {

  int EOF = 0;
  int NON_EXPRESSION_TEXT = 1;
  int START_EXPRESSION = 2;
  int INTEGER_LITERAL = 7;
  int FLOATING_POINT_LITERAL = 8;
  int EXPONENT = 9;
  int STRING_LITERAL = 10;
  int TRUE = 11;
  int FALSE = 12;
  int NULL = 13;
  int END_EXPRESSION = 14;
  int COLON = 15;
  int DOT = 16;
  int GT = 17;
  int LT = 18;
  int EQ = 19;
  int LE = 20;
  int GE = 21;
  int NE = 22;
  int LPAREN = 23;
  int RPAREN = 24;
  int LBRACKET = 25;
  int RBRACKET = 26;
  int PLUS = 27;
  int MINUS = 28;
  int MULTIPLY = 29;
  int DIVIDE = 30;
  int MODULUS = 31;
  int NOT = 32;
  int AND = 33;
  int OR = 34;
  int PAGE_CONTEXT = 35;
  int PAGE = 36;
  int REQUEST = 37;
  int SESSION = 38;
  int APPLICATION = 39;
  int PARAM = 40;
  int PARAMS = 41;
  int IDENTIFIER = 42;
  int IMPL_OBJ_START = 43;
  int LETTER = 44;
  int DIGIT = 45;

  int DEFAULT = 0;
  int IN_EXPRESSION = 1;

  String[] tokenImage = {
    "<EOF>",
    "<NON_EXPRESSION_TEXT>",
    "\"${\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"}\"",
    "\":\"",
    "\".\"",
    "<GT>",
    "<LT>",
    "\"==\"",
    "<LE>",
    "<GE>",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<DIVIDE>",
    "<MODULUS>",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"pageContext\"",
    "\"page\"",
    "\"request\"",
    "\"session\"",
    "\"application\"",
    "\"param\"",
    "\"params\"",
    "<IDENTIFIER>",
    "\"#\"",
    "<LETTER>",
    "<DIGIT>",
  };

}
